AWASS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('awss.urls')),
    path('accounts/', include('accounts.urls')), # for github
    path('authentication/', include('authentication.urls')),
    path('scanner', include('scanner.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')), # for Linkedin, Google, Facebook
    # path('', include('test1.urls')),
]

accounts/urls.py
from django.urls import path

app_name = 'account'

urlpatterns = [

]

authentication/urls.py
from django.urls import path

app_name = 'authenticator'

urlpatterns = [

]

awss/urls.py
from django.urls import path
from . import views
app_name = 'awss'

urlpatterns = [
    path('', views.home, name='awss-home'),
    path('service/', views.service, name='awss-service'),
    path('about/', views.about, name='awss-about'),
    path('contact/', views.contact, name='awss-contact'),
    path('login/', views.signin, name='awss-login'),
    path('signup/', views.signup, name='awss-signup'),
    path('scan/', views.scan, name='awss-scan'),
    path('signout/', views.signout, name='awss-signout'),
]

scanner/urls.py
from django.urls import path

app_name = 'scan'

urlpatterns = [

]

test1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
]

accounts/models.py
from django.db import models

# Create your models here.

authentication/models.py
from django.db import models

# Create your models here.

awss/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

scanner/models.py
from django.db import models

# Create your models here.

test1/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

authentication/views.py
from django.shortcuts import render

# Create your views here.

awss/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .models import Contact
from django.views.generic import TemplateView
# Create your views here.


def home(request):
    return render(request, 'awss/Home.html')


def service(request):
    return render(request, 'awss/Services.html')


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        description = request.POST['message']
        user_contact = Contact.objects.create(name=name, email=email, description=description)
        user_contact.save()
        return redirect('awss:awss-home')
    return render(request, 'awss/Contact.html')


def about(request):
    return render(request, 'awss/About.html')


def signin(request):
    if request.user.is_authenticated:
        return redirect('awss:awss-signout')
    else:
        if request.method == 'POST':
            user_name = request.POST['name']
            password = request.POST['Password']
            user = authenticate(request, username=user_name, password=password)
            if user is not None:
                login(request, user)
                return redirect('awss:awss-signout')
    return render(request, 'awss/Login.html')


def signout(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            logout(request)
            return redirect('awss:awss-login')
        return render(request, 'awss/Signout.html')
    return redirect('awss:awss-login')


def signup(request):
    if request.user.is_authenticated:
        return redirect('awss:awss-signout')
    if request.method == 'POST':
        user_name = request.POST['name']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        if pass1 == pass2:
            print(f'{user_name, email, pass1, pass2}')
            try:
                user_email = User.objects.get(email=email)
                print(f'{user_email.email} already exist')
            except User.DoesNotExist:
                try:
                    name_user = User.objects.get(username=user_name)
                    print(f'{name_user.username} already exist')
                except User.DoesNotExist:
                    user = User.objects.create_user(email=email, username=user_name, password=pass1)
                    user.save()
                    return redirect('awss:awss-login')
    return render(request, 'awss/Signup.html')


def scan(request):
    return render(request, 'awss/Scan.html')

scanner/views.py
from django.shortcuts import render

# Create your views here.

test1/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'test1/home.html')

templates/awss/Home.html
{% load static %}
<!DOCTYPE html>
<html style="font-size: 16px;">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="We Find And Report​">
    <meta name="description" content="">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/Home.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 4.12.21, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">


    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"logo": "{% static 'images/AutomatedWebSecurityScanner-logos_white.png' %}"
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Home">
    <meta property="og:type" content="website">
</head>
<body class="u-body u-xl-mode">
<header class="u-clearfix u-grey-75 u-header u-header" id="sec-a613">
    <div class="u-clearfix u-sheet u-sheet-1">
        <a href="{% url 'awss:awss-home' %}" class="u-image u-logo u-image-1" data-image-width="1200" data-image-height="1200">
            <img src="{% static 'images/AutomatedWebSecurityScanner-logos_white.png' %}" class="u-logo-image u-logo-image-1">
        </a>
        <nav class="u-menu u-menu-dropdown u-offcanvas u-menu-1" data-position="Home">
            <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
                <a class="u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
                    <svg class="u-svg-link" viewBox="0 0 24 24">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use>
                    </svg>
                    <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
                        <g>
                            <rect y="1" width="16" height="2"></rect>
                            <rect y="7" width="16" height="2"></rect>
                            <rect y="13" width="16" height="2"></rect>
                        </g>
                    </svg>
                </a>
            </div>
            <div class="u-custom-menu u-nav-container">
                <ul class="u-nav u-unstyled u-nav-1">
                    <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'awss:awss-home' %}" style="padding: 10px 20px;">Home</a>
                    </li>
                    <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'awss:awss-service' %}" style="padding: 10px 20px;">Services</a>
                    </li>
                    <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'awss:awss-contact' %}" style="padding: 10px 20px;">Contact</a>
                    </li>
                    <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'awss:awss-about' %}" style="padding: 10px 20px;">About</a>
                    </li>
                    <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'awss:awss-login' %}" style="padding: 10px 20px;">Login</a>
                    </li>
                    <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'awss:awss-signup' %}" style="padding: 10px 20px;">Signup</a>
                    </li>
                </ul>
            </div>
            <div class="u-custom-menu u-nav-container-collapse">
                <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
                    <div class="u-inner-container-layout u-sidenav-overflow">
                        <div class="u-menu-close"></div>
                        <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                            <li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'awss:awss-home' %}">Home</a>
                            </li>
                            <li class="u-nav-item"><a href="{% url 'awss:awss-service' %}" class="u-button-style u-nav-link">Services</a>
                            </li>
                            <li class="u-nav-item"><a href="{% url 'awss:awss-contact' %}" class="u-button-style u-nav-link">Contact</a>
                            </li>
                            <li class="u-nav-item"><a href="{% url 'awss:awss-about' %}" class="u-button-style u-nav-link">About</a>
                            </li>
                            <li class="u-nav-item"><a href="{% url 'awss:awss-login' %}" class="u-button-style u-nav-link">Login</a>
                            </li>
                            <li class="u-nav-item"><a href="{% url 'awss:awss-signup' %}" class="u-button-style u-nav-link">Signup</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
            </div>
        </nav>
    </div>
</header>
<section class="u-clearfix u-image u-section-1" id="sec-58f6" data-image-width="1200" data-image-height="1200">
    <div class="u-clearfix u-sheet u-sheet-1">
        <a href="{% url 'awss:awss-scan' %}"
           class="u-border-2 u-border-hover-palette-1-base u-border-palette-1-base u-btn u-btn-round u-button-style u-hover-palette-1-base u-none u-radius-50 u-text-black u-btn-1">Scan</a>
    </div>
</section>


<footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-7f4d">
    <div class="u-align-left u-clearfix u-sheet u-sheet-1">
        <div class="u-list u-list-1">
            <div class="u-repeater u-repeater-1">
                <div class="u-container-style u-list-item u-repeater-item">
                    <div class="u-container-layout u-similar-container u-container-layout-1">
                        <a href="mailto:l1f18bscs0388@ucp.edu.pk" class="u-active-none u-btn u-button-style u-custom-item u-hover-none u-none u-btn-1">
                            <span class="u-icon u-icon-1" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">
                                <svg class="u-svg-content" viewBox="0 0 24 16" x="0px" y="0px" style="width: 1em; height: 1em;">
                            <path fill="currentColor" d="M23.8,1.1l-7.3,6.8l7.3,6.8c0.1-0.2,0.2-0.6,0.2-0.9V2C24,1.7,23.9,1.4,23.8,1.1z M21.8,0H2.2
	c-0.4,0-0.7,0.1-1,0.2L10.6,9c0.8,0.8,2.2,0.8,3,0l9.2-8.7C22.6,0.1,22.2,0,21.8,0z M0.2,1.1C0.1,1.4,0,1.7,0,2V14
	c0,0.3,0.1,0.6,0.2,0.9l7.3-6.8L0.2,1.1z M15.5,9l-1.1,1c-1.3,1.2-3.6,1.2-4.9,0l-1-1l-7.3,6.8c0.2,0.1,0.6,0.2,1,0.2H22
	c0.4,0,0.6-0.1,1-0.2L15.5,9z"></path>
                        </svg>
                            <img>
                        </span>&nbsp;l1f18bscs0388@ucp.edu.pk
                        </a>
                    </div>
                </div>
                <div class="u-container-style u-list-item u-repeater-item">
                    <div class="u-container-layout u-similar-container u-container-layout-2">
                        <a href="mailto:l1f18bscs0495@ucp.edu.pk" class="u-active-none u-btn u-button-style u-custom-item u-hover-none u-none u-btn-2">
                            <br><span class="u-icon u-icon-2" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction=""><svg class="u-svg-content" viewBox="0 0 24 16" x="0px"
                                                                                                                                                                           y="0px" style="width: 1em; height: 1em;"><path
                                fill="currentColor" d="M23.8,1.1l-7.3,6.8l7.3,6.8c0.1-0.2,0.2-0.6,0.2-0.9V2C24,1.7,23.9,1.4,23.8,1.1z M21.8,0H2.2
	c-0.4,0-0.7,0.1-1,0.2L10.6,9c0.8,0.8,2.2,0.8,3,0l9.2-8.7C22.6,0.1,22.2,0,21.8,0z M0.2,1.1C0.1,1.4,0,1.7,0,2V14
	c0,0.3,0.1,0.6,0.2,0.9l7.3-6.8L0.2,1.1z M15.5,9l-1.1,1c-1.3,1.2-3.6,1.2-4.9,0l-1-1l-7.3,6.8c0.2,0.1,0.6,0.2,1,0.2H22
	c0.4,0,0.6-0.1,1-0.2L15.5,9z"></path></svg><img></span>&nbsp;l1f18bscs0495@ucp.edu.pk
                        </a>
                    </div>
                </div>
                <div class="u-container-style u-list-item u-repeater-item">
                    <div class="u-container-layout u-similar-container u-container-layout-3">
                        <a href="mailto:l1f17bscs0552@ucp.edu.pk" class="u-active-none u-btn u-button-style u-custom-item u-hover-none u-none u-btn-3"><span class="u-icon u-icon-3" data-animation-name=""
                                                                                                                                                             data-animation-duration="0" data-animation-delay="0"
                                                                                                                                                             data-animation-direction=""><svg class="u-svg-content"
                                                                                                                                                                                              viewBox="0 0 24 16" x="0px"
                                                                                                                                                                                              y="0px"
                                                                                                                                                                                              style="width: 1em; height: 1em;"><path
                                fill="currentColor" d="M23.8,1.1l-7.3,6.8l7.3,6.8c0.1-0.2,0.2-0.6,0.2-0.9V2C24,1.7,23.9,1.4,23.8,1.1z M21.8,0H2.2
	c-0.4,0-0.7,0.1-1,0.2L10.6,9c0.8,0.8,2.2,0.8,3,0l9.2-8.7C22.6,0.1,22.2,0,21.8,0z M0.2,1.1C0.1,1.4,0,1.7,0,2V14
	c0,0.3,0.1,0.6,0.2,0.9l7.3-6.8L0.2,1.1z M15.5,9l-1.1,1c-1.3,1.2-3.6,1.2-4.9,0l-1-1l-7.3,6.8c0.2,0.1,0.6,0.2,1,0.2H22
	c0.4,0,0.6-0.1,1-0.2L15.5,9z"></path></svg><img></span>&nbsp;l1f17bscs0552@ucp.edu.pk
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <span class="u-align-center u-icon u-text-palette-1-base u-icon-4"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 54.757 54.757" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink"
                                                                                                                                                                                  xlink:href="#svg-0a89"></use></svg><svg
                class="u-svg-content" viewBox="0 0 54.757 54.757" x="0px" y="0px" id="svg-0a89" style="enable-background:new 0 0 54.757 54.757;"><path d="M40.94,5.617C37.318,1.995,32.502,0,27.38,0c-5.123,0-9.938,1.995-13.56,5.617c-6.703,6.702-7.536,19.312-1.804,26.952
	L27.38,54.757L42.721,32.6C48.476,24.929,47.643,12.319,40.94,5.617z M27.557,26c-3.859,0-7-3.141-7-7s3.141-7,7-7s7,3.141,7,7
	S31.416,26,27.557,26z"></path></svg></span>
        <p class="u-align-center u-text u-text-default u-text-1">Lahore, Punjab, Pakistan</p>
    </div>
</footer>
</body>
</html>

templates/awss/Signout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign-out</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="u-btn u-btn-submit u-button-style">Logout</button>
</form>
</body>
</html>

templates/test1/home.html
{% extends 'test1/_base.html' %}
{% load static %}
{% block content %}
    <section class="u-clearfix u-palette-1-dark-1 u-section-1" id="sec-9b4f">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-align-center u-container-style u-layout-cell u-size-12 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <h4 class="u-text u-text-default u-text-1">Signup with:</h4>
                    <a href="{% url 'social:begin' 'google-oauth2' %}">
                        <img class="u-image u-image-default u-preserve-proportions u-image-1" src="{% static 'images/300221.png' %}" alt="" data-image-width="128" data-image-height="128">
                    </a>
                    <a href="{% url 'social:begin' 'linkedin-oauth2' %}">
                        <img class="u-image u-image-default u-preserve-proportions u-image-2" src="{% static 'images/145807.png' %}" alt="" data-image-width="128" data-image-height="128">
                    </a>
                  <img class="u-image u-image-default u-preserve-proportions u-image-3" src="{% static 'images/5968764.png' %}" alt="" data-image-width="128" data-image-height="128">
                </div>
              </div>
              <div class="u-container-style u-layout-cell u-size-10 u-layout-cell-2">
                <div class="u-container-layout u-container-layout-2">
                  <h4 class="u-text u-text-2">OR</h4>
                </div>
              </div>
              <div class="u-container-style u-layout-cell u-size-38 u-layout-cell-3">
                <div class="u-container-layout u-container-layout-3">
                  <div class="u-form u-form-1">
                    <form action="#" method="post" class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" source="custom" name="form" style="padding: 10px;">
                        {% csrf_token %}
                      <div class="u-form-group u-form-name">
                        <label for="name-5356" class="u-label">Username</label>
                        <input type="text" placeholder="Enter username" id="name-5356" name="name" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="">
                      </div>
                      <div class="u-form-email u-form-group">
                        <label for="email-5356" class="u-label">Email</label>
                        <input type="email" placeholder="Enter a valid email address" id="email-5356" name="email" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="">
                      </div>
                      <div class="u-form-group u-form-group-3">
                        <label for="text-5b38" class="u-label">Password</label>
                        <input type="password" placeholder="Enter Password" id="text-5b38" name="pass1" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="required">
                      </div>
                      <div class="u-form-group u-form-group-4">
                        <label for="text-8606" class="u-label">Password</label>
                        <input type="password" placeholder="Re-enter Password " id="text-8606" name="pass2" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required="required">
                      </div>
                      <div class="u-align-left u-form-group u-form-submit">
                          <button type="submit" class="u-btn u-btn-submit u-button-style">Signup</button>
                      </div>
                      <div class="u-form-send-message u-form-send-success"> Thank you! Your message has been sent. </div>
                      <div class="u-form-send-error u-form-send-message"> Unable to send your message. Please fix errors then try again. </div>
                      <input type="hidden" value="" name="recaptchaResponse">
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}